### ISSUE TITLE
iOS "Lmi/VidyoClient/VidyoConnector_Objc.h" file not found. When build it says file not found. 

### ISSUE THREAD

**Issue by emvigotech** [Vidyo/multiview-connector-ios#2]
![screen shot 2018-09-04 at 11 44 53 am](https://user-images.githubusercontent.com/26790656/45013362-7dcc5380-b038-11e8-88ad-4deb08093a33.png)

**Comment by tmelko-vidyo** [comment]
Hi,
Assume you have added **VidyoClientIOS.framework** to the "Linked Frameworks and Libraries" but it's possibly located in unknow for xcode folder. This error means that it cannot find the public headers which are located inside "~/VidyoClientIOS.framework/Headers/" somewhere under your custom path. The solution here is to add one more "Header Seach Paths" to "Build Settings".
Also please make sure that your **VidyoClientIOS.framework** is located under "Framework Search Path" as well because it will throw another exception (or fix it to follow your custom path)

**Comment by emvigotech** [comment]
Hi,
VidyoClientIOS.framework was not in this sample so downloaded it from the  SDK package for iOS.
Then I had to add the framework in the lib folder. After that I was able to build the project.

Thanks
